### ISSUE TITLE
Align visual layout (style) with Vamp UI

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-runner#30]

**Comment by olafmol** [comment]
@DHVAMP could you create a colour-scheme that is consistent with Vamp UI so we can apply it to the CSS

**Comment by DHVAMP** [comment]
Bij deze alle kleuren voor VAMP met HEX/RGB/CMYK

![colour-scheme](https://cloud.githubusercontent.com/assets/20397075/18582701/b4f6ba0c-7c06-11e6-8838-576dc1f8d119.jpg)
