### ISSUE TITLE
errors on autoscale recipe on Katana version 0.9.1-6-gfe664ba

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-runner#74]
when running the "autoscale" recipe using Vamp runner katana on Vamp docker quickstart Katana the 3th step, running the mock-metrics workflows throws this errors: 

I1206 10:36:04.143234 11103 exec.cpp:134] Version: 0.27.0
I1206 10:36:04.174814 11115 exec.cpp:208] Executor registered on slave f4d1d246-cf48-4cb6-8f8e-977473642bc1-S1
panic: Execution period must be specified and it must be equal or greater than 0.

goroutine 1 [running]:
panic(0x8cf080, 0xc42000bfe0)
	/usr/local/opt/go/libexec/src/runtime/panic.go:500 +0x1a1
github.com/op/go-logging.(*Logger).Panic(0xc4201026f0, 0xc420037d90, 0x1, 0x1)
	/Users/dragoslav/workspace/go/src/github.com/op/go-logging/logger.go:182 +0x160
main.checkInt(0xc42000bd50, 0x9cbe06, 0x19, 0x9d880e, 0x4a)
	/Users/dragoslav/workspace/go/src/github.com/magneticio/vamp-workflow-agent/main.go:111 +0x1d1
main.main()
	/Users/dragoslav/workspace/go/src/github.com/magneticio/vamp-workflow-agent/main.go:57 +0x15b

and:

--container="mesos-f4d1d246-cf48-4cb6-8f8e-977473642bc1-S1.5d6015d6-be1c-415c-b18c-5ec267c5e965" --docker="docker" --docker_socket="/var/run/docker.sock" --help="false" --initialize_driver_logging="true" --launcher_dir="/usr/libexec/mesos" --logbufsecs="0" --logging_level="INFO" --mapped_directory="/mnt/mesos/sandbox" --quiet="false" --sandbox_directory="/var/run/mesos/slave1/slaves/f4d1d246-cf48-4cb6-8f8e-977473642bc1-S1/frameworks/f4d1d246-cf48-4cb6-8f8e-977473642bc1-0001/executors/vamp_workflow-mock-metrics.c985c486-bb9f-11e6-a481-024237d3526a/runs/5d6015d6-be1c-415c-b18c-5ec267c5e965" --stop_timeout="10secs"
--container="mesos-f4d1d246-cf48-4cb6-8f8e-977473642bc1-S1.5d6015d6-be1c-415c-b18c-5ec267c5e965" --docker="docker" --docker_socket="/var/run/docker.sock" --help="false" --initialize_driver_logging="true" --launcher_dir="/usr/libexec/mesos" --logbufsecs="0" --logging_level="INFO" --mapped_directory="/mnt/mesos/sandbox" --quiet="false" --sandbox_directory="/var/run/mesos/slave1/slaves/f4d1d246-cf48-4cb6-8f8e-977473642bc1-S1/frameworks/f4d1d246-cf48-4cb6-8f8e-977473642bc1-0001/executors/vamp_workflow-mock-metrics.c985c486-bb9f-11e6-a481-024237d3526a/runs/5d6015d6-be1c-415c-b18c-5ec267c5e965" --stop_timeout="10secs"
Registered docker executor on 192.168.99.100
Starting task vamp_workflow-mock-metrics.c985c486-bb9f-11e6-a481-024237d3526a
[32m10:36:04.570 main NOTI ==> 
██╗   ██╗ █████╗ ███╗   ███╗██████╗
██║   ██║██╔══██╗████╗ ████║██╔══██╗
██║   ██║███████║██╔████╔██║██████╔╝
╚██╗ ██╔╝██╔══██║██║╚██╔╝██║██╔═══╝
 ╚████╔╝ ██║  ██║██║ ╚═╝ ██║██║
  ╚═══╝  ╚═╝  ╚═╝╚═╝     ╚═╝╚═╝
                       workflow agent
                       version katana
                       by magnetic.io
                                       [0m
[35m10:36:04.571 main CRIT ==> Execution period must be specified and it must be equal or greater than 0. [0m
  ╚═══╝  ╚═╝  ╚═╝╚═╝     ╚═╝╚═╝
                       workflow agent
                       version katana
                       by magnetic.io
                                       [0m
[35m10:36:04.571 main CRIT ==> Execution period must be specified and it must be equal or greater than 0. [0m
t must be equal or greater than 0. [0m

**Comment by olafmol** [comment]
the workflow definitions should be updated with the new env vars for:
  WORKFLOW_EXECUTION_PERIOD: 
  WORKFLOW_EXECUTION_TIMEOUT:

**Comment by dragoslav** [comment]
These vars get default values if they are not otherwise specified - something defined in Vamp configuration. Quick start image had a typo - pull the latest katana and it will work.
Also pull the latest runner katana - there was a change in JS.
